= Robot Hackathon - Python module
// Refs:
:url-ocp-basepath: {{OCP-BASEPATH}}
:url-ocpconsole: https://console-openshift-console.apps.{url-ocp-basepath}
:url-codeready: http://codeready-codeready.apps.{url-ocp-basepath}
:url-3scale: {{URL-3SCALE}}
:url-gogs: http://gitea-gitea.apps.{url-ocp-basepath}

== Welcome Python Developers!

Good choice of programming language team! With the help of Python you will control your robot in no time!

Robot Services Ltd has provided a basic Python application to 
quickly get you started with your first robot application. It’s provided in a GitHub repository. You may mirror this template project into your team’s Git (Gitea) repository running in OpenShift and start to developing in it.

== Migrate the Python Example into your Git Repo

. Open the {url-gogs}[Gitea^] web UI.
. Click on the `*+*` in the upper right and choose `*New Migration*`.
. Fill in the `*Clone Address*` field: `*https://github.com/cloud-native-robotz-hackathon/starter-app-python.git*`
. The `*Repository Name*` field should be `*starter-app-python*`
. Do *not* set the repo as mirror or as private!
. Click on `*Migrate Repository*`

== Configure and Run

In this Hackathon you'll use CodeReady Workspaces for development. You should already be logged-in to CodeReady Workspaces as your robot user.

To get started hacking you have to:

* Start a runtime-specific CodeReady development workspace containing the tools you need
* Have your code cloned into the development environment

You could start a workspace in CodeReady and clone your repo manually or use CodeReady's *devfile* mechanism. The *devfile* method is pretty cool, so we'll use it here.

=== Configure CodeReady Workspaces using a devfile

TIP: A devfile is a simple yaml file that describes your CodeReady Workspaces environment: the stack image to use, the Git repository to clone and more.

Your repository already contains a *devfile.yaml* (go to the Gitea web UI and have a look if you are interested). To use it:

* Go to the {url-gogs}[Gitea^] web UI again, open the new repo and copy the HTTP clone URL. 
* Open the *devfile.yaml* by clicking it and press the pencil icon to switch to edit mode. 
* In edit mode change 
----
location: 'https://github.com/cloud-native-robotz-hackathon/starter-app-python.git' 
----

to match your own repo url, e.g.:
----
location: 'http://gitea-gitea.apps.cluster-berlin-5375.berlin-5375.example.opentlc.com/terminator/starter-app-python.git' 
----

* Click the *Commit Changes* button


Now point CodeReady Workspaces to the *devfile.yaml* using a special URL in the form of *\http://codeready.url/f?url=http://gitrepo.url/devfile.yaml*. First get the raw URL of your devfile:

* Open it by clicking the *Raw* button in Gitea
* Copy the URL from your browser
* Open the URL in a new browser tab: 

[subs="attributes"]
----
{url-codeready}/f?url=&lt;your-devfile-raw-url> 
----

This will bring up an animated construction image while building your dev environment. Hit the *Back to Dashboard* link at the lower left, you will see your workspace being build in the CodeReady web UI. Click the workspace name and then *OPEN*. Watch your workspace building.

TIP: This can take a couple of minutes because it has to pull the stack image into OpenShift.

You are ready to go when the *Welcome To Your Workspace* comes up. 

* Close the welcome page (by clicking the *x*)
* Open the Explorer by choosing the pages icon in the menubar to the left
* Open the project directory *starter-app-python* with your source code.

TIP: The devfile did all this for you: Building the stack from a custom image, cloning the sources from your Gitea repository.

=== Basic Application Configuration

Because the application you cloned is a template, to make it work with your robot you have to configure the connection details first:

* Expand the project tree on the left and open the *config.py* file by double-clicking it
* Change the *URI* (if required) and the *APITOKEN* parameter
** You could look up the URI in your 3Scale account, it should look like this example: *\https://api-2445582274375.production.gw.apicast.io/api/robot*.
** For *APITOKEN* fill in your <robot name>

Now commit these code changes to Gitea:

In CodeReady click on the source control icon in the menubar to the left. This opens the Git view with the file *config.py* marked as changed. To stage, commit and push your changes:

* In the Source Control view, move your mouse pointer over the *CHANGES* bar and click the *+* sign to stage all changes.
* On the top bar *SOURCE CONTROL: GIT* press the check mark to commit the changes.
* You will be asked to enter a commit message
* Now push your changes by clicking the *...* button in the top bar and choose *Push* as operation. Enter your <robot name> as username and the password {{OCP-PASSWORD}}.

TIP: If you want to see the changes that you have just pushed to Gitea you can have a look at your current repository in the {url-gogs}[Gitea^] Web UI.

== First build in OpenShift.

You're ready to run the application the first time! But first make sure your team robot is connected to the power supply and switched on!

Again there is more then one way to deploy your application to OpenShift! We'll use the brand new *odo* ("OpenShift Do") command line client here, for other options see the end of this guide. The *odo* client is completely developer centric, it's capabilities are focused on building and deploying applications to OpenShift.

=== Configure *odo*

Bring up your dev environment in CodeReady Workspaces. If you closed it, open CodeReady, click the workspace and hit *OPEN*. Then in CodeReady Workspaces:

* Choose *Terminal* -> *Open Terminal in specific container*
* Choose the *Python* terminal

Now *in the terminal window* configure *odo* by running:

* `odo login \https://api.{url-ocp-basepath}:6443`
** Confirm insecure connection and then use your credentials (<robot name> and password) to login to OpenShift
* `odo project create <robot name>-python-dev` to create a new OpenShift project
* Change into your project/source directory: `cd /projects/starter-app-python/`
* Tell *odo* you are building a Python app: `odo create python`
* Create a URL to access your app: `odo url create --port 8080`
* Build and deploy the first version: `odo push`

Watch *odo* do all the work for you in CodeReady, or go to the OpenShift web console and have a look what's happening in your project (*Projects -> <robot name>-python-dev*).

After *odo* returns you are ready to access your application. Get the full URL to your app (called a *route* in OpenShift) either by running *odo describe* or by accessing the *Resources* tab of your projects *Workloads* page in the web console.

=== Check Robot

Open the *route* (URL) to your newly created application in your browser. It'll take you to the Python Robot Control Landing Page. From here you can execute a simple connectivity test of your robot by clicking *Status*. If this returns *OK*, your app can talk to your robot!

=== Run Robot!

To execute the *run* method click the *Run* button. Execution will take some seconds but then the robot should move some centimeters forward.

If the robot moved, your setup is good and ready to go for the Hackathon!

== Start Hacking

To get started with programming open the file *wsgi.py* and then edit the *run* method.

Currently our robot is driving 10 cm forward. We want to let it drive 15 cm, so go ahead and find the parameter where the distance is set and change it accordingly. Re-build the app with the new code using *odo* by running `odo push` again.  

After *odo* has finished reload your control application, hit the *Run* button and see if your code changes are in effect.

== Final Remarks

You might have noticed so far we didn't push our code changes to Gitea. This works fine as long as you use *odo* to push changes directly to OpenShift, but if you loose your CodeReady workspace for any reason your code changes will be gone. So better push to Gitea every now and then the way you did already.

As a true DevOps team you can be agile during development in your dev project. But for the prod release you'll have to provide a deployment based on a defined Git version using OpenShift's source-2-image build method. For now go through the training missions, we'll explain the source-2-image method at the end of this guide.

== Training Missions

Here are some training missions to get you started.

*Hints:*

* Plan what your robot should do, check the space for the square
* Look up the robot API calls you might need in 3Scale
* Add code in the *run* method and use *odo* to re-build the app
* Test your code by running it from the robot control page
* Push to Gitea regularly

As everything happens in HTTP requests, if you manage to get your program into an endless loop or so, the easiest way to terminate your application might be to scale the Pod down in the OpenShift console. An even better idea is to limit loop runs.

If you want to see e.g. debug messages you put into your code, open the Logs window of your Pod in Openshift.

=== Task: Make your robot drive in a square

Get your robot to drive in a square with approx 10 cm edge length.

WARNING: Solution Below!

+++ <details><summary> +++
*>> _Click here for the solution_ <<*
+++ </summary><div> +++

This is the most simple way your *run* method could look like. It's obviously not programmed in a smart way, that's what you are here for!

----
def run():
    data = {'user_key': application.config['APITOKEN']} 
    response = requests.post(application.config['URI'] + '/forward/10', data=data, verify=False)
    response = requests.post(application.config['URI'] + '/right/90', data=data, verify=False)
    response = requests.post(application.config['URI'] + '/forward/10', data=data, verify=False)
    response = requests.post(application.config['URI'] + '/right/90', data=data, verify=False)
    response = requests.post(application.config['URI'] + '/forward/10', data=data, verify=False)
    response = requests.post(application.config['URI'] + '/right/90', data=data, verify=False)
    response = requests.post(application.config['URI'] + '/forward/10', data=data, verify=False)
    return response.text
----

+++ </div></details> +++

=== Task: Make your robot stop before hitting the wall

Setup a barrrier/wall and program your robot so it moves to the wall but stops in time before hitting it. You'll need the forward() and distance() functions.

WARNING: Solution Below!

+++ <details><summary> +++
*>> _Click here for the solution_ <<*
+++ </summary><div> +++

This is again not programmed in a particularly smart way, it's just an intro. You can do better!

----
def run():
    data = {'user_key': application.config['APITOKEN']} 
    response = requests.get(application.config['URI'] + '/distance' + '?user_key=' + application.config['APITOKEN'], verify=False)
    while float(response.text) > 100:
        print (str(response.text))
        requests.post(application.config['URI'] + '/forward/5', data=data, verify=False)
        response = requests.get(application.config['URI'] + '/distance' + '?user_key=' + application.config['APITOKEN'], verify=False)
    return 'Wall coming up!'
----

+++ </div></details> +++

== Now the Fun Starts!

Okay, by now you should have:

* set up a complete Cloud Native Development Environment using Python as your programming language of choice  
* gone through some training missions to get you up to speed

You have all the information to get started hacking the robot!

=== Final Mission

As explained your mission will be to navigate your robot through an unkown labyrinth with a combination of driving and distance checks. So prepare and test your robot with different maze variations.

== Feature Freeze!

When it's time for the final challenge you have to build your production release.  

=== Build and Deploy App with Source-2-Image

To build the final release, follow these steps:

* Make sure your latest code version has been pushed to Gitea
* In the OpenShift console switch to the Developer persona by selecting *Developer* from the drop-down menu to the upper left.
* Create a new project for your production release by choosing *Projects* from the *Advanced* menu.
* Click the *Create Project* button and create a project named *<robot-name>-python-prod*
* Click *+Add* in the left menu and select the *From Git* tile
* Fill in the fields
** *Git Repo URL*: Clone URL from your Gitea repo
** Make sure *Git Type* is set to *Other*
** As *Builder Image* choose the Python tile (make sure version is 3.6)
** Under *General* *application* and *Name* are pre-filled, leave as is
* Finally hit the *Create* button!

You will be taken to the *Topology* view, the circular arrow icon indicates the running bild process. When the build has finished, is turns into a green check mark.

After the build has finished, open the application by clicking the top right icon to open it.

Good Luck and Robotz Go, Go, Go! 

== Links

{url-3scale}[3Scale Web UI^]

{url-ocpconsole}[OpenShift Web UI^]

{url-codeready}[CodeReady Workspaces Web UI^]

{url-gogs}[Gitea Web UI^]




