= Robot Hackathon - Python module
// Refs:
:url-ocp-basepath: {{OCP-BASEPATH}}
:url-ocpconsole: https://console-openshift-console.apps.{url-ocp-basepath}
:url-codeready: http://codeready-codeready.apps.{url-ocp-basepath}
:url-3scale: {{URL-3SCALE}}
:url-gogs: https://gitea-gitea.apps.{url-ocp-basepath}

== Welcome Python Developers!

Good choice of programming language team! With the help of Python you will control your robot in no time!

Robot Services Ltd has provided a basic Python application to 
quickly get you started with your first robot application. It’s provided in a GitHub repository. You may mirror this template project into your team’s Git (Gitea) repository running in OpenShift and start to developing in it.

== Migrate the Python Example into your Git Repo

. Login to your {url-gogs}[Gitea^] account with your teamname as username  and the provided password.
. Click on the `*+*` in the upper right and choose `*New Migration*`.
. Fill in the `*Clone Address*` field: `*https://github.com/cloud-native-robotz-hackathon/starter-app-python.git*`
. The `*Repository Name*` field should be `*starter-app-python*`
. Do *not* set the repo as mirror or as private!
. Click on `*Migrate Repository*`

== Configure and Run

In this Hackathon you'll use CodeReady Workspaces for development. You should already be logged-in to CodeReady Workspaces as your robot user.

To get started hacking you have to:

* Start a runtime-specific CodeReady development workspace containing the tools you need
* Have your code cloned into the development environment

You could use one of two options to do this in CodeReady Workspaces:

* Start a workspace in CodeReady from the list of available stacks and configure the project with a Git repository URL  
* Use CodeReady's *devfile* mechanism.

=== Configure CodeReady Workspaces using a devfile

TIP: A devfile is a simple yaml file that describes your CodeReady Workspaces environment: the stack image to use, the Git repository to clone and more.

Your repository already contains a *devfile.yaml* (go to the Gitea web UI and have a look if you are interested). To use it:

* Go to the Gitea web UI, open the new repo and copy the HTTPS clone URL. 
* Open the *devfile.yaml* by clicking it and press the pencil icon to switch to edit mode. 
* In edit mode change 
----
location: 'https://github.com/goetzrieger/starter-app-python.git' 
----

to match your own repo url, e.g.:
----
location: 'http://gitea-gitea.apps.cluster-berlin-5375.berlin-5375.example.opentlc.com/terminator/starter-app-python.git' 
----

* Click the *Commit Changes* button


Now point CodeReady Workspaces to the *devfile.yaml* using a special URL in the form of *http://codeready.url/f?url=http://gitrepo.url/devfile.yaml*. First get the raw URL of your devfile:

* Open it by clicking the *Raw* button in Gitea
* Copy the URL from your browser
* Open the URL in a new browser tab: 

----
{url-codeready}/f?url=<your-devfile-raw-url>
----

This will bring up an animated construction image while building your dev environment. Hit the *Back to Dashboard* link at the lower left, you will see your workspace being build in the CodeReady web UI. Click the workspace name and then *OPEN*. Watch your workspace building.

TIP: This can take a couple of minutes because it has to pull the stack image into OpenShift.

You are ready to go when the *Welcome To Your Workspace* comes up. 

* Close the welcome page (by clicking the *x*)
* Open the Explorer by choosing the pages icon in the menubar to the left
* Open the project directory with your source code.

TIP: The devfile did all this for you: Building the stack from a custom image, cloning the sources from your Gitea repository.

=== Basic Application Configuration

Because the application you cloned is a template to make it work with your robot you have to configure the connection details first:

* Expand the project tree on the left and open the *config.py* file by double-clicking it
* Change the *URI* and *APITOKEN* parameters
** You could look up the URI in your 3Scale account, it should look like this example: *https://api-2445582274375.production.gw.apicast.io/api/robot*.
** For *APITOKEN* fill in your team name to route your requests to the proper robot

Now commit these code changes to Gitea:

In CodeReady click on the source control icon in the menubar to the left. This opens the Git view with the file *config.py* marked as changed. To stage, commit and push your changes:

* In the Source Control view, move your mouse pointer over the *CHANGES* button and click the *+* sign to stage all changes.
* On the top bar labelled *SOURCE CONTROL: GIT* press the check mark to commit the changes.
* You will be asked to enter a commit message
* Now push your changes by clicking the *...* button in the top bar and choose *Push* as operation. Enter your Gitea username and password.

TIP: If you want to see the changes that you have just pushed to Gitea you can have a look at your current repository in the Gitea Web UI.

== First build in OpenShift.

You're ready to run the application the first time! But first make sure your team robot is connected to the power supply and switched on!

Again there is more then one way to deploy your application to OpenShift! We'll use the brand new *odo* ("OpenShift Do") command line client here, for other options see the end of this guide. The *odo* client is completely developer centric, it's capabilities are focused on building and deploying applications to OpenShift.

=== Configure *odo*

Bring up your dev environment in CodeReady Workspaces. If you closed it, open CodeReady, click the workspace and hit *OPEN*. Then in CodeReady Workspaces:

* Choose *Terminal* -> *Open Terminal in specific container*
* Choose the *Python* terminal

Now *in the terminal window* configure *odo* by running:

* `odo login https://api.{url-ocp-basepath}:6443`
** Use your credentials (robot name and password) to login to OpenShift
* `odo project create <robot name>-python` to create a new OpenShift project
* Change into your project/source directory: `cd /projects/starter-app-python/`
* Tell *odo* you are building a Python app: `odo create python`
* The app should be exposed: `odo url create --port 8080`
* And finally build the first version: `odo push`

Watch *odo* do all the work for you (basically doing a source-to-image build) in CodeReady, or go to the OpenShift web console as your robot user and have a look what's happening in your project.

After *odo* returns or the "app donut" in the web console (*Project* -> *Workloads* -> *Overview*) indicates one running Pod, you are ready to access your application. Get the app route either by running *odo describe* or by accessing the *Resources* tab of your projects *Workloads* page in the web console.

=== Check Robot

Open the route to your newly created application. It'll take you to the Python Robot Control Landing Page. From here you can execute a simple connectivity test of your robot by clicking *Status*. If this returns *OK*, your app can talk to your robot!

=== Run Robot!

To execute the *run* method click the `*Run*` button. Execution will take some seconds but then the robot should move some centimeters forward.

If the robot moved, your setup is good and ready to go for the Hackathon!

== Start Hacking

To get started with programming open the file *wsgi.py* and then edit the *run* method.

Currently our robot is driving 5 cm forward. We want to let is drive 10 cm, so go ahead and find the parameter where the distance is set and change it accordingly. Re-build the app with the new code using *odo* by running `odo push` again.  

After *odo* has finished reload your control application, hit the *Run* button and see if your code changes are in effect.

WARNING: You might have noticed so far we didn't push our code changes to the Gitea repository. This works fine as long as you use *odo* to push changes directly to OpenShift, but if your CodeReady workspace gets into trouble you might loose your changes. So better push to Gitea every now and then the same way you did already.

== Training Missions

Here are some training missions to get you started.

*Hints:*

* Plan what your robot should do, check the space for the square
* Look up the robot API calls you might need in 3Scale
* Add code in the *run* method and use *odo* to re-build the app
* Test your code by running it from the robot control page
* Push to Gitea regularly

As everything happens in HTTP requests, if you manage to get your program into an endless loop or so, the easiest way to terminate your application might be to scale the Pod down in the OpenShift console. An even better idea is to limit loop runs.

If you want to see e.g. debug messages you put into your code, open the Logs window of your Pod in Openshift.

=== Task: Make your robot drive in a square

Get your robot to drive in a square with approx 10 cm edge length.

WARNING: Solution Below!

+++ <details><summary> +++
*>> _Click here for the solution_ <<*
+++ </summary><div> +++

This is the most simple way your *run* method could look like. It's obviously not programmed in a smart way, that's what you are here for!

----
def run():
    data = {'user_key': application.config['APITOKEN']} 
    response = requests.post(application.config['URI'] + '/forward/10', data=data, verify=False)
    response = requests.post(application.config['URI'] + '/right/90', data=data, verify=False)
    response = requests.post(application.config['URI'] + '/forward/10', data=data, verify=False)
    response = requests.post(application.config['URI'] + '/right/90', data=data, verify=False)
    response = requests.post(application.config['URI'] + '/forward/10', data=data, verify=False)
    response = requests.post(application.config['URI'] + '/right/90', data=data, verify=False)
    response = requests.post(application.config['URI'] + '/forward/10', data=data, verify=False)
    return response.text
----

+++ </div></details> +++

=== Task: Make your robot stop before hitting the wall

Setup a barrrier/wall and program your robot so it moves to the wall but stops in time before hitting it. You'll need the forward() and distance() functions.

WARNING: Solution Below!

+++ <details><summary> +++
*>> _Click here for the solution_ <<*
+++ </summary><div> +++

This is again not programmed in a particularly smart way, it's just an intro. You can do better!

----
def run():
    data = {'user_key': application.config['APITOKEN']} 
    response = requests.get(application.config['URI'] + '/distance' + '?user_key=' + application.config['APITOKEN'], verify=False)
    while float(response.text) > 100:
        print (str(response.text))
        requests.post(application.config['URI'] + '/forward/5', data=data, verify=False)
        response = requests.get(application.config['URI'] + '/distance' + '?user_key=' + application.config['APITOKEN'], verify=False)
    return 'Wall coming up!'
----

+++ </div></details> +++

=== Optional: Clone Gogs Repo into CodeReady Workspace

If you don't have {url-codeready}[CodeReady^] open in your browser, login as your team. Then open the `Workspace` you already created: choose it in the *Dashboard* or *Workspaces* view and click the *OPEN* button in the upper right corner. 

To start a new project with your sources from Gogs:

* Click `*Import Project*`, choose `GIT` as Version Control System.
* Paste your GIT Project URL from Gogs. Get it by copying the HTTP URL from your Gogs account, it should look like `*{url-gogs}/<GUID>/<GUID>-python.git*`
* Edit the link and add your username and passwort to it for push authentication. It should now look like this: `*http://<GUID>:<PASSWORD>@{url-gogs}/<GUID>/<GUID>-python*`
* Click on `*Import*`
* In the project configuration window that comes up next leave or set to `*Blank*`
* Click `*Save*`.

In addition you have to edit the GIT user profile in Che: 

* In the menu choose `*Profile->Prereferences*`
* Select `*GIT Committer*`
* Enter `*<GUID>*` in the name field and `*<GUID>@example.com*` in the E-Mail field. 
* Click on `*Save*` and close the Window.

Now is a good time to have a first look at the Python template application. It's deliberately simple as it's just meant to be a starting point. It's based on the Flask framework, it creates a simple webpage with a button to allow you to execute a method *run*. 

=== Optional: Build app from source without *odo*

Open the {url-ocpconsole}[OpenShift Web UI^]. If not already logged in, log in with `*<robot name>*` and the provided password.

. Click on the `*<GUID>-project*`
. Click on *Browse Catalog* -> *Languages* -> *Python* and choose `*Phython*`.
. Click on `*Next*`
. As Python version keep 3.6
. As `Application Name` use `*<GUID>-phython*` and as `GIT Repository` use `*{url-gogs}/<GUID>/<GUID>-python*`
. Click on `*Create*` and `*Close*`
. Click on `*Overview*` and then on the little `*>*` beside the `Deployment Config`.
. You can watch the build steps in the lower right console
. The application is deployed an ready when you see a blue circle indicating the number of healthy pods with you app



