= Robot Hackathon - Java module
//refs
:url-ocp-basepath: {{OCP-BASEPATH}}
:url-gogs: http://gogs-hackathon.apps.{url-ocp-basepath}
:url-ocpconsole: https://master.{url-ocp-basepath}/console
:url-codeready: http://codeready-hackathon.apps.{url-ocp-basepath}
:url-3scale: {{3SCALE_URL}}


Welcome to the Quarkus module. You choose wisely as Java is still one of the most popular programming languages around.  

Robot Services Ltd has provided a basic Quarkus-based Java application template to 
quickly get you started with your first robot application. It's provided in a 
GitHub repository. You will migrate this template project into your team's Git (Gogs) repository running in OpenShift and start to developing in it.

To migrate the template project into Gogs:

* Go to the Gogs Url in you browser: {url-gogs}[Gogs^]
* Click *Sign In* in the top right corner 
* Log in
** Username : <GUID>
** Password : <The standard password provided>
* In the top right corner click on the plus sign (Create) and choose *New Migration* 
* Enter
** *Clone Address :* https://github.com/cloud-native-robotz-hackathon/starter-app-java-quarkus.git
** *Repository Name :* <GUID>-robot-app
* Make sure the repository is set to *public*
* Keep the rest as is
* Click on *Migrate Repository*

Now you have the application template in your team's git repository and can get started with hacking. For this you need to clone your repository into your Development Environment (CodeReady Workspaces) running on OpenShift.

To clone you repository into CodeReady : 

* Go back to CodeReady : {url-codeready}[CodeReady^]
* Log in (if required) by clicking on OpenShift v3
** Username : <GUID>
** Password : <The standard password provided>
* If you just loggend in again you can find you previously created workspace on the left
** Doubleclick *<GUID>-robot-app-workspace* to open the workspace again        
* Once your workspace is ready, click *Import Project*
** You can also find this option in the top menu *Workspace > Import Project*
* In the *Import project* window:
** Choose *GIT*
** *URL of your Git repo*: {url-gogs}/<GUID>/<GUID>-robot-app.git
** *Name*: 
* In the next dialog choose *Java -> Maven*
* Click *Save*

==== Login *oc* to OpenShift from CodeReady workspace

Before deploying applications from your CodeReady workspace to OpenShift, you have to 
login with the OpenShift CLI-client (oc) into the OpenShift environment. The fabric8 Maven plugin will use the existing oc connection to deploy you application directly into your OpenShift project. 

Get the login string from the OpenShift web UI:

* In the web UI, click the top right question mark, choose *Command Line Tools*
* Now a form opens, copy the *oc login...* string *using the copy button*
* Accept the self signed certificate with *y*
* Go to the CodeReady Terminal window in lower workspace pane and paste the command, then press *Enter*
* You should see a welcome message as you are now logged into OpenShift
* Try running `oc whoami` to make sure you are logged in

=== Running the Application Locally

*Open a new terminal* in your CodeReady workspace by clicking the *+* sign and *Terminal* in the 
lower workspace pane. Change into your project directory:

----
cd /projects/<GUID>-app
----

Now build and run the application locally by executing this Maven command:

----
mvn compile quarkus:dev
----

WARNING: You should do this in a new terminal window because you can't stop the 
application with Ctrl-C.

Now your application should run in the embedded Tomcat server. To access the 
application web frontend, look up the URL:

* Again using the *+* sign, open a *Servers* view.
* Under *Reference* search for *8080/tcp*
* Click the URL in the row to the right, this will take you to the web page of your application

By clicking the *Run* button you start the *run* method of the application. 
Using the initial check out this will print a log message you will see in the 
terminal Tomcat is running in.

=== Changing the Application

Now it's time to make the first change to the application code. The code 
structure is standard-Maven, have a look around. The log message you just 
saw is triggered in the *run()* method of Java class 
`../src/main/java/io/openshift/booster/service/RobotEndpoint.java`

TIP: CodeReady behaves similar to IDEs like Eclipse, VSCode and IntelliJ.  Expand the directory structure tree on the left side until you see the file *RobotEndpoint.java* 

As a first example go and change the log message and the standard output:

----
public Object run() {
        System.out.println("Hello <GUID> Team");
        String response = "Hello <GUID> Team";
        // Example GET invokation of the Robot API
----

Open a new terminal, change to the <GUID>-app directory as before and enter

----
mvn compile quarkus:dev
----

This will compile the changed Java files and Quarkus boot will take care of hot-swapping your code change into the running server.

Wait until this has finished and run again by pressing *Run* on the web page.

Do this as long as you want, the goal is to get familiar with the process.

TIP: When you are finished changing code, close the terminal Tomcat is running 
in.

=== Deploying the Application to OpenShift

Until now the application runs locally in your CodeReady workspace. To run it as a 
containerized service in OpenShift, deployable where ever you want, you have to 
build and deploy a container image from your application. And guess what? It's 
easy!

To deploy to OpenShift, in the terminal enter and run:

----
mvn clean package -DuberJar
oc login -u <username> -p <password>
oc project <teamname>-robot-app
oc new-build registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.5 --binary --name=<teamname>-robot-app -l app=starter-app-java-quarkus
oc start-build <teamname>-robot-app --from-file target/*-runner.jar --follow
oc expose service <teamname>-robot-app

Finally, make sure it's actually done rolling out:
oc rollout status -w dc/<teamname>-robot-app
----

  

This will compile your Java code, create a Docker image from it, push the image to the OpenShift container registry and then deploy it to your OpenShift project. This time, the command will return because the code was deployed in a 
container/pod in OpenShift. Go to the OpenShift web console and open your 
project. You might see the build still running. The application is running successfully when you see the blue circle. The 
route to externally access the application will be visible in the upper right 
corner. It will look like:

----
http://hub-controller-live-<GUID>-project.apps.{url-ocp-basepath} 
----

Clicking the route will take you to your applications web page again. But this 
time in the running in cloud!

Try running the *run()* method again, it should do the same as before. To see 
the log message, click the blue circle with the pod name in the OpenShift Console and click on the 
*Logs* tab. This is also the first place to look at when your checking for issues
with you deployed application.

TIP: As you may know the buildtool Maven downloads a lot of Java libraries for you application
from the internet.  This takes some time during the first compile so be patient. To speed up the subsequent compiles, add the option -o to the command. This will tell Maven to work in offline mode, as it has already downloaded alll required libaries. 

Now your basic development and deployment workflow is ready. 

== Training Mission

=== Task: Make your robot drive in a square with approx 20cm edge length

Hints:

* Plan what your robot should do, check the space for the square.
* Look up the API calls you need (remember the API documentation?)
* Change the code in the *run()* method (have a look at the commented out code 
examples for REST POST and Get Requests)
* Test locally in CodeReady if you want to
* Be aware that the motors and sensors of the robot are not a 100% precise. So you may need to add some adjustment to your turns and moves.
* Deploy to OpenShift and run

+++ <details><summary> +++
*>> _Click here for the solution_ <<*
+++ </summary><div> +++

----
 MultiValueMap<String, String> paramMap = new LinkedMultiValueMap<String, 
String>();
        paramMap.add("user_key", "<API Key>");
        HttpEntity<MultiValueMap<String, String>> request = new 
HttpEntity<MultiValueMap<String, String>>(paramMap,
                new LinkedMultiValueMap<String, String>());
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/forward/20", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/left/90", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/forward/20", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/left/90", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/forward/20", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/left/90", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/forward/20", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/left/90", request, String.class);
----

+++ </div></details> +++

=== Task: Make your robot stop before hitting the wall

Setup a barrrier/wall and program your robot so it moves to the wall but stops in time before hitting it. You'll need the forward() and distance() functions.

+++ <details><summary> +++
*>> _Click here for the solution_ <<*
+++ </summary><div> +++


This is again not programmed in a particularly smart way, it's just an intro. Feel free to enhance!

Notice the exit criteria after 10 loops to make sure we are not running into an endless loops.  

----
 MultiValueMap<String, String> paramMap = new LinkedMultiValueMap<String, String>();
        paramMap.add("user_key", "<GUID>");
        HttpEntity<MultiValueMap<String, String>> request = new HttpEntity<MultiValueMap<String, String>>(paramMap,
                new LinkedMultiValueMap<String, String>());
        
    int loopCount = 0;
    System.out.println("Initial distance " + restTemplate.getForObject(hubControllerEndpoint + "/distance?user_key=<GUID>", String.class));
    
    while (Integer.valueOf(restTemplate.getForObject(hubControllerEndpoint + "/distance?user_key=<GUID>", String.class)) > 100 && loopCount < 10  )
    {
        
        System.out.println("Loop run " + i + " , current distance " + restTemplate.getForObject(hubControllerEndpoint + "/distance?user_key=r2d2", String.class));
        
        response = restTemplate.postForObject(hubControllerEndpoint + "/forward/5", request, String.class);
        loopCount++;
                
    }
----

+++ </div></details> +++

TIP: You may wrap your REST calls into functions to make them easier to use

Now return to the main instruction document 