= Robot Hackathon - PHP module
//refs
:url-ocp-basepath: {{OCP-BASEPATH}}
:url-ocpconsole: https://master.ratingen-d48f.open.redhat.com/console
:url-codeready: http://codeready-hackathon.apps.ratingen-d48f.open.redhat.com
:url-3scale: {{3SCALE_URL}}

== Welcome php developers!

Good choice Team <GUID>! With the help of php you will crush all the other Teams!

Robot Services Ltd has provided a basic php application to 
quickly get you started with your first robot application.

. Login into http://gogs-hackathon.apps.ratingen-d48f.open.redhat.com[Gogs^] with `*<GUID>*` and the provided password.
. Click on the `*+*` in the upper right and choose `*New Migration*`.
. In the `*Clone Address*` field write `*https://github.com/Tuxos/robot-hackathon-starter-app-php*`
. In the `*Repository Name*` field write `*<GUID>-php*`
. Click on `*Migrate Repository*`

Go to your `*<GUID>-php*` project and edit the `*config.php*`.

Change the API Key to your 3Scale API Key: `*$apikey = "<GUID>";*`

Click on `*Commit changes*`.

In http://codeready-hackathon.apps.ratingen-d48f.open.redhat.com[Eclipse Che^] open your `Workspace` click on `*Import Project*`, choose `GIT` as Version Control System.

In the `*URL*` field paste your GIT Project from Gogs. It should be: `*http://gogs-hackathon.apps.ratingen-d48f.open.redhat.com/<GUID>/<GUID>-php*`.

Edit the link and add your username and passwort to it. It should look like this: `*http://<GUID>:<PASSWORD>@gogs-hackathon.apps.ratingen-d48f.open.redhat.com/<GUID>/<GUID>-php*`

Don't forget to use the password which was provided to you.

Click on `*Import*` and choose `*PHP*`, then click `*Save*`.

We must edit the GIT user profile. For that click on `*Profile*`, `*Prereferences*`, choose `*GIT Committer*` enter `*<GUID>*` in the name field and `*<GUID>@example.com*` in the E-Mail field. Click on `*Save*` and close the Window.

Let's have a first build in OpenShift.

Open the https://master.ratingen-d48f.open.redhat.com/console[OpenShift Web UI^]. If not already logged in, log in with `*<GUID>*` and the provided password.

. Click on the `*<GUID>-project*`
. Click on `*Browse Catalog*`, `*Languages*`, `*PHP*`, `*PHP*` again.
. Click on `*Next*`
. As `Application Name` use `*<GUID>-php*` and as `GIT Repository` use `*http://gogs-hackathon.apps.ratingen-d48f.open.redhat.com/<GUID>/<GUID>-php*`
. Click on `*Create*` and `*Close*`
. Click on `*Overview*` and then on the little `*>*` beside the `Deployment Config`.

After the build is complete, click the Link to your new created Application.

Now you see the PHP Robocontroll Landingpage. From here you can test some basic functionalities.

If you click on the green `*Run*` butten, he will execute the `*run.php*` script from the Gogs project.

To edit the `*run.php*` script, go to Eclipse Che, expand the `*<GUID>-project*` and double click on `*run.php*`.

Edit the script as wanted.

Then click on `*Git*`, `*Commit*`, choose a Commit message as you want. Don't forget to click on the `*Push commited changes*` checkmark. Then click on `*Commit*`.

In OpenShift rebuild you application and test the new `run.php` script.

== Challenge

*Task:* Make your robot drive in a square with approx 20cm edge length

*Hints:*

* Plan what your robot should do, check the space for the square.
* Look up the php calls you need (look at the landingpage or in `run.php`)
* Change the code in `run.php` and commit it with Eclipse Che
* Keep in mind that motors ans sensors of the robot are not 100 % precise, so you may need to compensate in your code
* Deploy to OpenShift
* Test your `run.php`

WARNING: Solution (for run.php) Below!
----
<?php

  forward(20);
  turnright(90);
  forward(20);
  turnright(90);
  forward(20);
  turnright(90);
  forward(20);
  turnright(90); 
  
?>
----

