= Robot Hackathon Lab Guide

This projects contains the lab guides to be deployed on the Hackathon OpenShift Cluster.  Ist is based on [Workshopper](https://github.com/openshift-evangelists/workshopper) which is an engine for building a web-based workshop 
or lab guide. 


== File Structure

=== `_modules.yml`
Lists all labs, their dependencies and where the lab content is hosted (GitHub, web server, etc). Note that this file has to be in the root of the repository.

=== `_hackathon1.yml`
A yaml file with that specifies which labs should be included in the rendered workshop guide. Note that the lab names should already be listed in `_modules.yml`. It goes without saying that you can have multiple of these yaml files to customize your workshop for different purposes.

===  `*.adoc`
The actual lab instructions depending on which markup language you have chosen (specified in `_modules.yml`). Note that the name of the file should be the exact same name as the key in `_modules.yml`.

## Deploy On OpenShift


```
$ oc new-app quay.io/osevg/workshopper --name=hackathon-lab-guide \
      -e WORKSHOPS_URLS="https://raw.githubusercontent.com/siamaksade/workshopper-template/master/_workshop1.yml" \
      -e JAVA_APP=false 
$ oc expose svc/hackathon-lab-guide
```

The lab content (`.adoc` files) will be pulled from the GitHub when users access the workshopper in 
their browser.

Note that the workshop variables can be overriden via specifying environment variables on the container itself e.g. the `JAVA_APP` env var in the above command

## Test Locally with Docker

You can directly run Workshopper as a docker container which is specially helpful when writing the content.
```
$ podman run -p 8080:8080 -v $(pwd):/app-data \
              -e CONTENT_URL_PREFIX="file:///app-data:z" \
              -e WORKSHOPS_URLS="file:///app-data/_hackathon1.yml" \
              quay.io/osevg/workshopper
```

Go to http://localhost:8080 on your browser to see the rendered workshop content. You can modify the lab instructions 
and refresh the page to see the latest changes.