= Robot Hackathon
// Refs:
:url-ocp-basepath: {{OCP-BASEPATH}}
:url-ocpconsole: https://console-openshift-console.apps.{url-ocp-basepath}
:url-codeready: http://codeready-codeready.apps.{url-ocp-basepath}
:url-3scale: {{URL-3SCALE}}
:url-gogs: http://gitea-gitea.apps.{url-ocp-basepath}

== Introduction

Welcome Team!

You are a special mission super coder/geek. Your mission is to complete 
several assignements using a state-of-the-art robot in a dangerous environment. 
The robot is provided by Robot Services, Ltd. Because speed is of utmost 
importance you will utilize agile and DevOps based development 
methodologies. To get productive quickly you will use the container 
platform OpenShift which will be provided by Robot Services. 

== Your Adventure starts... connect to the Robot

=== Access the API

Robot Service Ltd provides access to their robots through an API gateway based 
on the 3Scale API Management platform.

TIP: As the robots are accessed over a public API, it's important to 
restrict and limit who can use the API. The API management platform takes care 
of role-based access control, setting up accounts, monitoring, routing, traffic 
shaping and more.

WARNING: Please access all the follwing URLs as a team on one laptop (not individually), as you are now a DevOps 
team and want to be on the same page. Also the cloud system is sized for one account per team performance wise. 

Okay, let's get started. Head over to the {url-3scale}[3Scale web UI^] and:

* Click on `*SIGN IN*` in the upper right
* Login with your credentials (your <robot name> and password : {{OCP-PASSWORD}}
* After login you will see the API key you need to access the robot API

TIP: Look around in the 3Scale web UI, you will see examples of how to invoke 
the API of your robot. 3Scale will take care of routing your requests to the 
Hub-Controller which in turn accesses your robot. 

WARNING: The most important information is the *Key* from the *Credentials* 
box. Using this key as parameter *user_key* in your API calls takes care of routing the requests to the proper robot. 

==== Testing the API

The easiest way to test the connection to the Hub-Controller is to use the 
curl commandline example found under the section *Run your requests*. Try this command in you terminal. This will test the connection to the Hub-Controller, *not* the robot!

The commandline to run and the output should resemble this example:
----
curl https://api-2445582274375.production.gw.apicast.io:443/api/robot/status?user_key=<robot name>
OK
----

If you don't have a laptop with the `curl`-command don't worry, you can test this also through the 3Scale webinterface in the next section.

==== Exploring the Robot API

There are a number of ways to test the connectivity from your PC via 3Scale to 
the robot. You basically need to construct an URL to query the API using 
the 3Scale *Key*.

While in the 3Scale web UI access the *DOCUMENTATION* link in the menu bar. 
Here you will find the REST API documentation of all robot operation currently 
exposed in OpenAPI/Swagger format.

You can test the available API calls from here. These will actually go to your 
robot. Just remember to fill in `*<robot name>*` as *USER_KEY* when you test.

TIP: Why don't you let the little guy drive around for a few cm?

=== Accessing OpenShift

Now that you can access and control your robot through the API let's get 
started with programming the robot by developing applications on our container 
platform. 

Your team user has already been created for you, your user name is `*<robot name>*`. Click {url-ocpconsole}[here^] to access the OpenShift web UI.

* Login as your team user, `*<robot name>*`, and password : {{OCP-PASSWORD}}
* Accept the self-signed certificate in you browser 
* Look around the OpenShift Console

That's it for now, we'll come back later, no worries.

=== Accessing the Git Repository

As Git repository we're using Gitea, an Open Source Git server. Gitea runs as container application in OpenShift, of course. To access Gitea:

* Open {url-gogs}[Gitea^] in your browser
* Login with `*<robot name>*`, and password : {{OCP-PASSWORD}}

=== Your first application

So we are ready to start with some coding. Normally you would now have to setup your 
dev environment on your laptop... install IDE, language runtimes, build tools, version control system/access, checkout code.... etc. And most of this would be specific to your OS.

Because we work in a cutting edge environment we'll use CodeReady Workspaces, a browser-based, cloud-native IDE running in the OpenShift environment.

To access CodeReady in your browser click {url-codeready}[here^]. Then:

* Login with your robot's name as username and the password : {{OCP-PASSWORD}}.
* On first login a page *Authorize Access* will come up, just click the *Allow selected permissions* button.
* On the next page you have to update some account information:
** *Email*: <robot name>@example.com
** *First name*: <robot name>
** *Last name*: <robot name> 
** Click *Submit*

TIP: Authentication for CodeReady Workspaces is handled by Red Hat Single Sign-On. You have to go through these steps once to grant access. 

==== The Time has come: Choose your Runtime

You are in the Workspace management view of CodeReady Workspaces now. CodeReady Workspaces provides development environments for several languages and runtimes, so you finally have to decide what runtime to use for programming your robot.

TIP: You can choose between Java, Python and NodeJS. Every runtime comes with a template to get you started!

==== Open the Runtime-Specific Guide 

Depending on your programming language choice, please refer to one of the following guides on how to set up your application and get started:

* Java Springboot Robot App
// * Java Quarkus Robot App
* NodeJS Robot App
* Python Robot App
// * PHP Robot App

Start the guide by clicking the name in the side bar.

== Links

{url-3scale}[3Scale Web UI^]

{url-ocpconsole}[OpenShift Web UI^]

{url-codeready}[CodeReady Workspaces Web UI^]

{url-gogs}[Gitea Web UI^]








